---
resources:
- name: rails-sample
  type: git
  source:
    uri: git@github.com:Esfahan/rails-sample.git
    private_key: {{github-private-key}}
    branch: feature/concourse-ci

- name: capistrano-sample
  type: git
  source:
    uri: git@github.com:Esfahan/capistrano-sample.git
    private_key: {{github-private-key}}
    branch: feature/concourse-ci

jobs:
- name: rails-job
  public: true
  plan:
    - get: rails-sample
      trigger: true
    - task: build
      file: rails-sample/ci/tasks/build.yml

- name: capistrano-job
  public: true
  plan:
    - get: rails-sample
      passed: [ rails-job ]
    - get: capistrano-sample
      trigger: true
    - task: deploy
      file: rails-sample/ci/tasks/deploy.yml
      params:
        GIT_SSH_KEY: {{github-private-key}}
