---
resources:
- name: rails-sample
  type: git
  source:
    uri: git@github.com:Esfahan/rails-sample.git
    private_key: {{github-private-key}}
    branch: feature/concourse-ci

- name: capistrano-sample
  type: git
  source:
    uri: git@github.com:Esfahan/capistrano-sample.git
    private_key: {{github-private-key}}
    branch: feature/concourse-ci

- name: build-cache
  type: s3
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: {{aws-bucket}}
    endpoint: {{aws-s3-endpoint}}
    disable_ssl: true
    use_v4: true

jobs:
- name: rails-job
  public: true
  plan:
    - get: rails-sample
      trigger: true
    - task: build
      file: rails-sample/ci/tasks/build.yml

- name: capistrano-job
  public: true
  plan:
    - get: build-cache
      trigger: true
    - get: rails-sample
      passed: [ rails-job ]
    - get: capistrano-sample
      trigger: true
    - task: deploy
      file: rails-sample/ci/tasks/deploy.yml
      params:
        GIT_SSH_KEY: {{github-private-key}}
    - put: build-cache
      params:
        file: store-cache
