---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.1
inputs:
  - name: rails-sample
  - name: build-cache
outputs:
  - name: store-cache
run:
  path: rails-sample/ci/scripts/build.sh
