---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.1
inputs:
  - name: rails-sample
  - name: capistrano-sample 
run:
  path: rails-sample/ci/scripts/deploy.sh
